version: 3.0.0

services:
  web:
    ports:
      - 3000:3000
    restart: always
    build:
      context: .
      dockerfile: DockerFile
    networks:
      - mangaland_network
    volumes:
      - .:/app
    command: sh -c "npm install && npm run start"
    container_name: mangaland

networks:
  mangaland_network:
    driver: bridge