import type { Metadata } from "next";
import { Geist, Geist_Mono, Kanit } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar/Navbars";

const kanit = Kanit({
    weight: ["100", "200", "400", "600"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${kanit.className} antialiased`}>
                <Navbar />
                <div className="container px-10 my-10 md:px-20">{children}</div>
            </body>
        </html>
    );
}
